import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yasiin - Use Pretemplate Yasiin</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        landing page for yasiin here
      </main>
    </div>
  )
}
